[package]
name = "helion-proj"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
helion-device = { workspace = true }
helion-ir = { workspace = true }
helion-bits = { workspace = true }
helion-pack = { workspace = true }
helion-place = { workspace = true }
helion-route = { workspace = true }
helion-hw = { workspace = true }
helion-sta = { workspace = true }
helion-debug = { workspace = true }
