[package]
name = "helion-vhdl"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
helion-ir = { workspace = true }
helion-sv = { workspace = true }

[dev-dependencies]
helion-device = { workspace = true }
helion-pack = { workspace = true }
helion-place = { workspace = true }
helion-route = { workspace = true }
helion-bits = { workspace = true }
helion-fabric = { workspace = true }
